# Generated by Django 4.2.1 on 2023-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fotografia_cantidad_fotografia_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
