# Generated by Django 4.2.1 on 2023-07-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fotografia_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='cantidad',
        ),
    ]
